import type { AppState, ExpenseKind } from "./types";

export const DEMO_PASSWORD = "demo1234";

function receiptImage(label: string) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="160" height="160"><rect fill="#f3e6dc" width="100%" height="100%"/><text x="50%" y="54%" text-anchor="middle" fill="#5c3b2e" font-size="26" font-family="Tahoma">${label}</text></svg>`;
  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`;
}

function sitePhoto(label: string, fill: string) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="640" height="480"><rect fill="${fill}" width="100%" height="100%"/><text x="50%" y="50%" text-anchor="middle" fill="#44403c" font-size="28" font-family="Tahoma">${label}</text></svg>`;
  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`;
}

/** بذرة تجربة كاملة لاختبار كل مسارات Daftar */
export function createSeedState(): AppState {
  return {
    unlocked: false,
    clients: [
      {
        id: "cli_mona",
        name: "منى عادل",
        phone: "+20 1005551234",
        notes: "عميلة شقة التجمع — من غير بريد عشان تجربة الدعوة",
        createdAt: "2024-10-01T10:00:00.000Z",
      },
      {
        id: "cli_ahmed",
        name: "أحمد حسن العزب",
        phone: "+20 1099887766",
        email: "ahmed.azab@example.com",
        notes: "فيلا المعادي — فيه شريط مصروفات غير مغطاة",
        createdAt: "2024-08-01T10:00:00.000Z",
      },
      {
        id: "cli_nour",
        name: "نور إبراهيم",
        phone: "+20 1112223334",
        email: "nour@example.com",
        createdAt: "2024-11-01T10:00:00.000Z",
      },
      {
        id: "cli_free",
        name: "عميل بدون مشاريع",
        phone: "+20 1000001111",
        email: "free.client@example.com",
        notes: "جاهز لتجربة الحذف من الدليل",
        createdAt: "2025-01-15T10:00:00.000Z",
      },
      {
        id: "cli_done",
        name: "هاني فتحي",
        phone: "+20 1223344556",
        email: "hany@example.com",
        createdAt: "2024-06-01T10:00:00.000Z",
      },
    ],
    contractors: [
      {
        id: "ctr_karim",
        name: "كريم فؤاد",
        phone: "+20 1001112233",
        specialties: ["بلاط"],
        notes: "مقاول بلاط شقة التجمع",
        active: true,
        createdAt: "2024-10-05T10:00:00.000Z",
      },
      {
        id: "ctr_naggash",
        name: "سامح يوسف",
        phone: "+20 1000112233",
        specialties: ["نقاشة", "بلاط"],
        notes: "نقاشة فيلا المعادي",
        active: true,
        createdAt: "2024-08-05T10:00:00.000Z",
      },
      {
        id: "ctr_sebaka",
        name: "هشام فاروق",
        phone: "+20 1222334455",
        specialties: ["سباكة"],
        active: true,
        createdAt: "2024-08-06T10:00:00.000Z",
      },
      {
        id: "ctr_idle",
        name: "مقاول تجربة حذف",
        phone: "+20 1555000111",
        specialties: ["بلاط"],
        notes: "من غير مشروع — جرّب الحذف",
        active: false,
        createdAt: "2025-02-01T10:00:00.000Z",
      },
    ],
    suppliers: [
      {
        id: "sup_noor",
        name: "معرض النور",
        phone: "+20 1009876543",
        email: "noor@example.com",
        specialties: ["بلاط", "رخام"],
        notes: "مورد سيراميك شقة التجمع",
        createdAt: "2024-10-08T10:00:00.000Z",
      },
      {
        id: "sup_tiles",
        name: "معرض السيراميك — المعادي",
        phone: "+20 1555667788",
        specialties: ["بلاط"],
        createdAt: "2024-08-08T10:00:00.000Z",
      },
      {
        id: "sup_paint",
        name: "دهانات النور",
        phone: "+20 1666778899",
        specialties: ["دهانات"],
        createdAt: "2024-08-09T10:00:00.000Z",
      },
      {
        id: "sup_free",
        name: "مورد بدون مشتريات",
        phone: "+20 1002223334",
        email: "supplier.free@example.com",
        specialties: ["حديد"],
        notes: "جاهز لتجربة الحذف",
        createdAt: "2025-02-02T10:00:00.000Z",
      },
    ],
    categories: [
      { id: "cat_tiles", name: "بلاط", color: "#e67e22" },
      { id: "cat_wood", name: "نجارة", color: "#8e44ad" },
      { id: "cat_paint", name: "نقاشة", color: "#2980b9" },
      { id: "cat_plumb", name: "سباكة", color: "#16a085" },
      { id: "cat_plaster", name: "محارة", color: "#d4a017" },
      { id: "cat_gypsum", name: "جبس", color: "#7d8c6a" },
      { id: "cat_marble", name: "رخام", color: "#8d99ae" },
      { id: "cat_elec", name: "كهرباء", color: "#c0392b" },
      { id: "cat_other", name: "متنوع", color: "#7f8c8d" },
    ],
    projects: [
      {
        id: "prj_tagamoa",
        name: "شقة التجمع",
        address: "التجمع الخامس — القاهرة",
        clientId: "cli_mona",
        status: "active",
        contractType: "percent",
        contractTotal: 850000,
        supervisionPct: 12,
        showClientPortal: true,
        showClientMoney: true,
        showClientGallery: true,
        showClientPrivatePhotos: false,
        showClientTxNotes: true,
        createdAt: "2024-10-02T10:00:00.000Z",
      },
      {
        id: "prj_maadi",
        name: "فيلا المعادي - تشطيبات",
        address: "المعادي — القاهرة",
        clientId: "cli_ahmed",
        status: "active",
        contractType: "percent",
        contractTotal: 2500000,
        supervisionPct: 12,
        showClientPortal: true,
        showClientMoney: true,
        showClientGallery: true,
        showClientPrivatePhotos: true,
        showClientTxNotes: false,
        createdAt: "2024-08-01T10:00:00.000Z",
      },
      {
        id: "prj_zayed",
        name: "شقة الشيخ زايد",
        address: "الشيخ زايد — الجيزة",
        clientId: "cli_nour",
        status: "active",
        contractType: "fixed",
        contractTotal: 780000,
        supervisionPct: 0,
        supervisionAmount: 50000,
        showClientPortal: true,
        showClientMoney: true,
        showClientGallery: false,
        showClientPrivatePhotos: false,
        showClientTxNotes: false,
        createdAt: "2024-11-05T10:00:00.000Z",
      },
      {
        id: "prj_nasr",
        name: "شقة مدينة نصر",
        address: "مدينة نصر — القاهرة",
        clientId: "cli_ahmed",
        status: "not_started",
        contractType: "contract",
        contractTotal: 650000,
        supervisionPct: 0,
        showClientPortal: false,
        showClientMoney: false,
        showClientGallery: false,
        createdAt: "2025-01-20T10:00:00.000Z",
      },
      {
        id: "prj_paused",
        name: "فيلا الساحل — معلق",
        address: "الساحل الشمالي",
        clientId: "cli_nour",
        status: "paused",
        contractType: "percent",
        contractTotal: 1200000,
        supervisionPct: 10,
        showClientPortal: false,
        createdAt: "2024-07-01T10:00:00.000Z",
      },
      {
        id: "prj_done",
        name: "شقة المهندسين — مكتمل",
        address: "المهندسين — الجيزة",
        clientId: "cli_done",
        status: "done",
        contractType: "percent",
        contractTotal: 400000,
        supervisionPct: 10,
        showClientPortal: true,
        showClientMoney: true,
        showClientGallery: true,
        showClientPrivatePhotos: false,
        showClientTxNotes: true,
        createdAt: "2024-03-01T10:00:00.000Z",
      },
    ],
    transactions: [
      // شقة التجمع — أرقام جولة مُعَمِّر: مستلم ١٥٠٬٠٠٠ · مصروف ١٠٬٥٠٠ · مستحق ١٬٢٦٠ · متبقي ١٣٨٬٢٤٠
      {
        id: "tx_tag_pay",
        projectId: "prj_tagamoa",
        type: "client_payment",
        amount: 150000,
        date: "2024-10-10T10:00:00.000Z",
        notes: "دفعة تحت الحساب",
        paymentClass: "expense",
        createdAt: "2024-10-10T10:00:00.000Z",
      },
      {
        id: "tx_tag_buy",
        projectId: "prj_tagamoa",
        type: "expense",
        amount: 2500,
        transportAmount: 0,
        storageAmount: 0,
        date: "2024-10-12T11:00:00.000Z",
        notes: "شراء سيراميك من معرض النور",
        categoryId: "cat_tiles",
        attachmentDataUrl: receiptImage("فاتورة"),
        expenseKind: "purchase" satisfies ExpenseKind,
        supplierId: "sup_noor",
        createdAt: "2024-10-12T11:00:00.000Z",
      },
      {
        id: "tx_tag_labor",
        projectId: "prj_tagamoa",
        type: "expense",
        amount: 8000,
        date: "2024-10-15T14:00:00.000Z",
        notes: "مدفوعات لـ كريم فؤاد",
        privateNotes: "دفعة أولى على بلاط الصالة",
        categoryId: "cat_tiles",
        attachmentDataUrl: receiptImage("سند"),
        expenseKind: "labor",
        contractorId: "ctr_karim",
        createdAt: "2024-10-15T14:00:00.000Z",
      },

      // فيلا المعادي — شريط مصروفات غير مغطاة (مثال NUMBERS)
      {
        id: "tx_ma_pay1",
        projectId: "prj_maadi",
        type: "client_payment",
        amount: 250000,
        date: "2024-08-05T12:00:00.000Z",
        notes: "دفعة تحت الحساب",
        paymentClass: "expense",
        createdAt: "2024-08-05T12:00:00.000Z",
      },
      {
        id: "tx_ma_pay2",
        projectId: "prj_maadi",
        type: "client_payment",
        amount: 45000,
        date: "2024-08-06T12:00:00.000Z",
        notes: "جزء من نسبة الإشراف",
        paymentClass: "supervision",
        createdAt: "2024-08-06T12:00:00.000Z",
      },
      {
        id: "tx_ma_exp1",
        projectId: "prj_maadi",
        type: "expense",
        amount: 150000,
        transportAmount: 5000,
        storageAmount: 3000,
        date: "2024-08-12T09:00:00.000Z",
        notes: "شراء بلاط",
        privateNotes: "سعر المتر قبل الخصم",
        categoryId: "cat_tiles",
        attachmentDataUrl: receiptImage("فاتورة"),
        expenseKind: "purchase",
        supplierId: "sup_tiles",
        createdAt: "2024-08-12T09:00:00.000Z",
      },
      {
        id: "tx_ma_exp2",
        projectId: "prj_maadi",
        type: "expense",
        amount: 25000,
        date: "2024-08-20T16:00:00.000Z",
        notes: "مصنعيات بلاط",
        categoryId: "cat_tiles",
        attachmentDataUrl: receiptImage("سند"),
        expenseKind: "labor",
        contractorId: "ctr_naggash",
        createdAt: "2024-08-20T16:00:00.000Z",
      },
      {
        id: "tx_ma_exp3",
        projectId: "prj_maadi",
        type: "expense",
        amount: 70000,
        transportAmount: 4000,
        storageAmount: 0,
        date: "2024-08-22T10:00:00.000Z",
        notes: "خشب أبواب",
        categoryId: "cat_wood",
        attachmentDataUrl: receiptImage("فاتورة"),
        expenseKind: "purchase",
        createdAt: "2024-08-22T10:00:00.000Z",
      },
      {
        id: "tx_ma_exp4",
        projectId: "prj_maadi",
        type: "expense",
        amount: 42000,
        date: "2024-08-25T15:00:00.000Z",
        notes: "خامات سباكة",
        categoryId: "cat_plumb",
        attachmentDataUrl: receiptImage("فاتورة"),
        expenseKind: "purchase",
        supplierId: "sup_paint",
        createdAt: "2024-08-25T15:00:00.000Z",
      },
      {
        id: "tx_ma_exp5",
        projectId: "prj_maadi",
        type: "expense",
        amount: 12550,
        date: "2024-08-26T15:00:00.000Z",
        notes: "مصنعية نقاشة إضافية",
        categoryId: "cat_paint",
        attachmentDataUrl: receiptImage("سند"),
        expenseKind: "labor",
        contractorId: "ctr_naggash",
        createdAt: "2024-08-26T15:00:00.000Z",
      },

      // زايد — عقد مبلغ إشراف ثابت
      {
        id: "tx_za_pay",
        projectId: "prj_zayed",
        type: "client_payment",
        amount: 200000,
        date: "2024-11-12T10:00:00.000Z",
        notes: "دفعة أولى",
        paymentClass: "expense",
        createdAt: "2024-11-12T10:00:00.000Z",
      },
      {
        id: "tx_za_exp",
        projectId: "prj_zayed",
        type: "expense",
        amount: 32000,
        transportAmount: 1500,
        storageAmount: 500,
        date: "2024-11-15T12:00:00.000Z",
        notes: "محارة وكهرباء ابتدائي",
        categoryId: "cat_elec",
        attachmentDataUrl: receiptImage("فاتورة"),
        expenseKind: "purchase",
        supplierId: "sup_tiles",
        createdAt: "2024-11-15T12:00:00.000Z",
      },

      // مشروع مكتمل
      {
        id: "tx_done_pay",
        projectId: "prj_done",
        type: "client_payment",
        amount: 400000,
        date: "2024-05-01T10:00:00.000Z",
        notes: "تسوية نهائية",
        paymentClass: "expense",
        createdAt: "2024-05-01T10:00:00.000Z",
      },
      {
        id: "tx_done_exp",
        projectId: "prj_done",
        type: "expense",
        amount: 280000,
        date: "2024-04-20T10:00:00.000Z",
        notes: "تشطيب كامل",
        categoryId: "cat_other",
        expenseKind: "purchase",
        createdAt: "2024-04-20T10:00:00.000Z",
      },
    ],
    agreements: [
      {
        id: "agr_karim",
        projectId: "prj_tagamoa",
        contractorId: "ctr_karim",
        amount: 40000,
        notes: "بلاط الصالة والحمامات",
        createdAt: "2024-10-08T10:00:00.000Z",
      },
      {
        id: "agr_naggash",
        projectId: "prj_maadi",
        contractorId: "ctr_naggash",
        amount: 51000,
        notes: "نقاشة الدور الأول ومصنعيات البلاط",
        createdAt: "2024-08-18T10:00:00.000Z",
      },
      {
        id: "agr_sebaka",
        projectId: "prj_maadi",
        contractorId: "ctr_sebaka",
        amount: 30000,
        notes: "سباكة الدور الأرضي — لسه بانتظار الدفع",
        createdAt: "2024-08-19T10:00:00.000Z",
      },
    ],
    albums: [
      {
        id: "alb_ceramic",
        projectId: "prj_tagamoa",
        name: "صور السيراميك",
        description: "مشترك مع العميل",
        sharedWithClient: true,
        coverPhotoId: "ph_ceiling",
        createdAt: "2024-10-14T09:00:00.000Z",
      },
      {
        id: "alb_trial",
        projectId: "prj_tagamoa",
        name: "ألبوم تجربة",
        description: "خاص بالمكتب",
        sharedWithClient: false,
        createdAt: "2024-10-16T09:00:00.000Z",
      },
      {
        id: "alb_empty",
        projectId: "prj_tagamoa",
        name: "ألبوم فاضي",
        sharedWithClient: false,
        createdAt: "2024-10-17T09:00:00.000Z",
      },
      {
        id: "alb_reception",
        projectId: "prj_maadi",
        name: "الريسبشن - مرحلة أولى",
        description: "صور الأرضية بعد التوريد",
        sharedWithClient: true,
        coverPhotoId: "ph_maadi_1",
        createdAt: "2024-08-14T09:00:00.000Z",
      },
      {
        id: "alb_private",
        projectId: "prj_maadi",
        name: "ملاحظات المكتب",
        description: "مش للعميل",
        sharedWithClient: false,
        createdAt: "2024-08-18T09:00:00.000Z",
      },
    ],
    photos: [
      {
        id: "ph_ceiling",
        projectId: "prj_tagamoa",
        dataUrl: sitePhoto("سقف الصالة", "#d6d3d1"),
        albumId: "alb_ceramic",
        caption: "سقف الصالة",
        sharedWithClient: true,
        hiddenFromClient: true,
        createdAt: "2024-10-14T10:00:00.000Z",
      },
      {
        id: "ph_tissues",
        projectId: "prj_tagamoa",
        dataUrl: sitePhoto("علبة المناديل", "#e7e5e4"),
        albumId: "alb_ceramic",
        caption: "علبة المناديل",
        sharedWithClient: true,
        createdAt: "2024-10-14T11:00:00.000Z",
      },
      {
        id: "ph_trial",
        projectId: "prj_tagamoa",
        dataUrl: sitePhoto("صورة خاصة", "#f5e6d3"),
        albumId: "alb_trial",
        caption: "تجربة ألبوم خاص",
        sharedWithClient: false,
        createdAt: "2024-10-16T10:00:00.000Z",
      },
      {
        id: "ph_loose",
        projectId: "prj_tagamoa",
        dataUrl: sitePhoto("كل الوسائط", "#cfe8d8"),
        caption: "صورة من غير ألبوم — قسم كل الوسائط",
        sharedWithClient: false,
        createdAt: "2024-10-18T10:00:00.000Z",
      },
      {
        id: "ph_maadi_1",
        projectId: "prj_maadi",
        dataUrl: sitePhoto("صور الموقع — بلاط", "#d6d3d1"),
        albumId: "alb_reception",
        caption: "توريد بلاط الصالة",
        sharedWithClient: true,
        createdAt: "2024-08-14T10:00:00.000Z",
      },
      {
        id: "ph_maadi_2",
        projectId: "prj_maadi",
        dataUrl: sitePhoto("ملاحظة داخلية", "#e7e5e4"),
        albumId: "alb_private",
        caption: "ملاحظة داخلية للمكتب",
        sharedWithClient: false,
        createdAt: "2024-08-18T10:00:00.000Z",
      },
    ],
  };
}
